### PR TITLE
Clean up extension support in different mediawiki instances

### PR DESCRIPTION
**Pull request by dsestero**
Hi, I'm glad you returned to work on this project. I made some fixes concerning mediawiki extensions that would ask you to pull. They are described in the commit comments and allow the code to be consistent in all the operations with respect to the current mediawiki instance and the current extension.

Thank you.

Dario

### CODE REVIEW

**Comment by aimonb** [comment]
Thank you for all the updates!

**Comment by dsestero** [comment]
Hi Aimon, I think something went wrong with your repository puppet-mediawiki or I don't understand.
This morning when I checked out your master I saw it points to 09233bbf035999fc4b4384caf0edb7c045acb81f commit, of 2014-03-19 18:35:17 with the comment: 'Adjust licensing to Apache 2.0'. This is strange, since when I branched out dsestero/fix_extensions, the branch with my last updates (3 commits), on July 1st I remember your master pointed to commit: b4cae0cbcd7306e6dd1d2b80651b5bdea6444fde, of 2015-06-25 21:18:48, 'Merge pull request #3 from ilomon/fixMailParamQuoting'.

Furthermore, I do not see my branch merged neither by looking at the Git history nor in the network graph GitHub offers. However my pull request was marked by GitHub as 'closed'. That's weird.
It seems like a piece of history with 27 commits from you, Ilona Blanck and me since 8th July, 2014 up to 1st July 2015 was lost.

Finally, I don't understand what is commit feacbe2 mentioned by GitHub in the merge of my pull request.

Could you please check and possibly explain to me?

Thank you
Dario Sestero

**Comment by dsestero** [comment]
Would you neeed it, the master branch of my public repo forked from your at the time of pull request #5 is aligned.

Best regards,
Dario Sestero

**Comment by aimonb** [comment]
Hi @dsestero it seems our internal CI overwrote the activity on this side. We are currently using your commit to rsync to. Sorry for the snafu, things should be sorted shortly.

**Comment by aimonb** [comment]
@dsestero I realized we would lose your name in the PR if we manually sync it. Can you please resubmit the PR?

**Comment by aimonb** [comment]
I have hand merged your code internally. Once it goes through CI and testing it will be pushed here. HEAD of your form should be roughly the same as HEAD here once we have pushed the merged code.

**Comment by dsestero** [comment]
Hi Aimon. I was out of office for a couple of weeks. Today I looked at your
code but it seems to me that several modifications were lost. Below you
find a summary of the most relevant differences and then the detailed git
diff.

What do you suggest to do?

Thanks,

Dario Sestero

### Summary

instance name in order to refer to different extensions
[manifests/files.pp]: owner and group attributes hardcode 'apache' instead
of using mediawiki::params::apache_user variable
[manifests/init.pp]: the name 'ConfirmAccount' is hardcoded instead of
using the variable containing the name of the extension
[manigests/instance.pp]: the rdoc and the default value is missing for a
bunch of parameters; owner and group attributes hardcode 'apache' or repeat
the test on the operatingsystem fact instead of using
mediawiki::params::apache_user variable
[manigests/params.pp]:a couple of variables are defined for later use
[Modulesfile]: this file is deprecated since Puppet 3.6
[metadata.json]: operatingsystem_support and tags attributes missing; types
and checksum attributes are deprecated since Puppet 3.6

### Detailed diff

dario@kauai:~/PuppetProjects/puppetmodules/puppet-mediawiki$ git diff
HEAD..upstream/master
diff --git a/.project b/.project
deleted file mode 100644
index 3e79283..0000000
--- a/.project
+++ /dev/null
@@ -1,23 +0,0 @@
-<?xml version="1.0" encoding="UTF-8"?>
-<projectDescription>
-    <name>nexusis_mediawiki</name>
-    <comment></comment>
-    <projects>
-    </projects>
-    <buildSpec>
-        <buildCommand>
-            <name>org.eclipse.xtext.ui.shared.xtextBuilder</name>
-            <arguments>
-            </arguments>
-        </buildCommand>

## \-        <buildCommand>

<name>com.puppetlabs.geppetto.pp.dsl.ui.modulefileBuilder</name>
-            <arguments>
-            </arguments>
-        </buildCommand>
-    </buildSpec>
-    <natures>
-        <nature>com.puppetlabs.geppetto.pp.dsl.ui.puppetNature</nature>
-        <nature>org.eclipse.xtext.ui.shared.xtextNature</nature>
-    </natures>
  -</projectDescription>
  diff --git a/Modulefile b/Modulefile
  new file mode 100644
  index 0000000..6037b45
  --- /dev/null
  +++ b/Modulefile
  @@ -0,0 +1,14 @@
  +name    'aimonb/nexusis_mediawiki'
  +version '2.0.4'
  +source 'https://github.com/NexusIS/puppet-mediawiki.git'
  +author 'Aimon Bustardo'
  +license 'Apache 2.0'
  +summary 'Puppet module for multi-tenant Mediawiki installation.'
  +description 'Deploy and manage multiple Mediawiki instances using only one
  installation.'
  +project_page 'https://github.com/NexusIS/puppet-mediawiki'
  +
  +## Add more dependencies, if any:
  +dependency 'puppetlabs/apache', '>= 0.4.0'
  +dependency 'puppetlabs/mysql', '>= 0.5.0'
  +dependency 'saz/memcached', '>= 2.0.0'
  +dependency 'puppetlabs/stdlib', '>= 3.0.0'
  diff --git a/lib/puppet/provider/mediawiki_extension/mediawiki_extension.rb
  b/lib/puppet/provider/mediawiki_extension/mediawiki_extension.rb
  index fba3d87..62a687a 100644
  --- a/lib/puppet/provider/mediawiki_extension/mediawiki_extension.rb
  +++ b/lib/puppet/provider/mediawiki_extension/mediawiki_extension.rb
  @@ -27,7 +27,7 @@
  Puppet::Type.type(:mediawiki_extension).provide(:mediawiki_extension) do
  end
  
  def exists?
-    File.exists?("#{doc_root}/#{instance}/extensions/#{name}/#{name}.php")
-    File.exists?("#{doc_root}/extensions/#{name}/#{name}.php")
  end

@@ -43,6 +43,6 @@
Puppet::Type.type(:mediawiki_extension).provide(:mediawiki_extension) do
   end

   def destroy
-    rm('-rf', "#{doc_root}/#{instance}/extensions/#{name}")
-    rm('-rf', "#{doc_root}/extensions/#{name}")
  end
  end
  diff --git a/manifests/files.pp b/manifests/files.pp
  index 1c7a5bf..4a58875 100644
  --- a/manifests/files.pp
  +++ b/manifests/files.pp
  @@ -26,8 +26,8 @@ define mediawiki::files (
  ) {
  file { $name:
   ensure  => link,
-    owner   => "${mediawiki::params::apache_user}",
-    group   => "${mediawiki::params::apache_user}",
-    owner   => 'apache',
-    group   => 'apache',
   mode    => '0755',
   target  => gen_target_path($target_dir, $name),
  }
  diff --git a/manifests/init.pp b/manifests/init.pp
  index 8992b75..baed617 100644
  --- a/manifests/init.pp
  +++ b/manifests/init.pp
  @@ -43,22 +43,22 @@ define mediawiki::manage_extension(
  $doc_root
  ){
  $extension = $name
-  $line = "require_once( \"\$IP/extensions/${extension}/${extension}.php\"
  );"
-  $line = "require_once(
  \"${doc_root}/${instance}/extensions/ConfirmAccount/ConfirmAccount.php\" );"
  $path = "${doc_root}/${instance}/LocalSettings.php"
  -
  +
  mediawiki_extension { $extension:
   ensure    =>  present,
-    instance  =>  $instance,
-    instance  =>  $wiki_name,
   source    =>  $source,
-    doc_root  =>  $doc_root,
-    doc_root  =>  $doc_root,
   notify  =>  Exec["set_${extension}_perms"],
  }
  
  file_line{"${extension}_include":
-    ensure  =>  $ensure,
   line    =>  $line,
-    ensure  =>  $ensure,
   path    =>  $path,
-    require =>  Mediawiki_extension["${extension}"],
-    require =>  Mediawiki_extension['ConfirmAccount'],
   notify  =>  Exec["set_${extension}_perms"],
  }
  File_line["${extension}_include"] ~> Service<| title == 'httpd' |>
  @@ -68,12 +68,12 @@ define mediawiki::manage_extension(
   notify  =>  Exec["set_${extension}_perms_two"],
  }
  exec{"set_${extension}_perms_two":
-    command     =>  "/bin/chown -R
  ${mediawiki::params::apache_user}:${mediawiki::params::apache_user}
  ${mediawiki::params::conf_dir}/${instance}",
-    command     =>  "/bin/chown -R
  ${mediawiki::params::apache_user}:${mediawiki::params::apache_user}
  /etc/mediawiki/${instance}",
   refreshonly =>  true,
   notify  =>  Exec["set_${extension}_perms_three"],
  }
  exec{"set_${extension}_perms_three":
-    command     =>  "/bin/chown -R
  ${mediawiki::params::apache_user}:${mediawiki::params::apache_user}
  ${mediawiki::params::mediawiki_install_path}",
-    command     =>  "/bin/chown -R
  ${mediawiki::params::apache_user}:${mediawiki::params::apache_user}
  /var/www/html/mediawiki_",
   refreshonly =>  true
  }
  }
  @@ -95,17 +95,17 @@ class mediawiki (
  $tarball_name             = regsubst($tarball_url,
  '^._?/(mediawiki-\d.\d+._tar.gz)$', '\1')
  $mediawiki_dir            = regsubst($tarball_url,
  '^._?/(mediawiki-\d.\d+.\d+).*$', '\1')
  $mediawiki_install_path   = "${web_dir}/${mediawiki_dir}"
  -
  +
  # Specify dependencies
  Class['mysql::server'] -> Class['mediawiki']
  #Class['mysql::config'] -> Class['mediawiki']
  -
-  class { 'apache':
  +
-  class { 'apache':
   mpm_module => 'prefork',
  }
  class { 'apache::mod::php': }
  -
  -
  +
  +
  # Manages the mysql server package and service by default
  class { 'mysql::server':
   root_password => $db_root_password,
  @@ -120,12 +120,12 @@ class mediawiki (
  file { 'mediawiki_conf_dir':
   ensure  => 'directory',
   path    => $mediawiki::params::conf_dir,
-    owner   => "${mediawiki::params::apache_user}",
-    group   => "${mediawiki::params::apache_user}",
-    owner   => 'apache',
-    group   => 'apache',
   mode    => '0755',
   require => Package[$mediawiki::params::packages],

## \-  }
-  }
  +
  # Download and install MediaWiki from a tarball
  exec { "get-mediawiki":
   cwd       => $web_dir,
  @@ -133,16 +133,16 @@ class mediawiki (
   creates   => "${web_dir}/${tarball_name}",
   subscribe => File['mediawiki_conf_dir'],
  }
  -
  +
  exec { "unpack-mediawiki":
   cwd       => $web_dir,
   command   => "/bin/tar -xvzf ${tarball_name}",
   creates   => $mediawiki_install_path,
   subscribe => Exec['get-mediawiki'],
  }
  -
  +
  class { 'memcached':
   max_memory => $max_memory,
   max_connections => '1024',
  }
  -}
  +}
  diff --git a/manifests/instance.pp b/manifests/instance.pp
  index 7a3275b..db0cfb6 100644
  --- a/manifests/instance.pp
  +++ b/manifests/instance.pp
  @@ -4,28 +4,14 @@
  #
  # === Parameters
  #
  -# [_db_name_]                - name of the mediawiki instance mysql
  database
  -# [_db_user_]                - name of the mysql database user
  -# [_db_password_]            - password for the mysql database user
  -# [_ip_]                     - ip address of the mediawiki web server
  -# [_port_]                   - port on mediawiki web server
  -# [_server_aliases_]         - an array of mediawiki web server aliases
  -# [_ensure_]                 - the current status of the wiki instance
  -#                            - options: present, absent, deleted
  -# [_db_prefix_]              - prefix of the table names for the instance
  database
  -#                              Defaults to +wk+
  -# [_allow_html_email_]       - whether html is allowed in email
  -# [_additional_mail_params_] - not used at the moment
  -# [_logo_url_]               - the logo url or pathname where '/' is the
  root directory of the wiki farm
  -# [_external_smtp_]          - whether an SMTP server is present and needs
  to be configurated for sending emails
  -# [_smtp_idhost_]            - the domain name to be used when sending
  emails
  -# [_smtp_host_]              - where the SMTP server is located; could be
  an IP address or a fqdn
  -# [_smtp_port_]              - port to use when connecting to the SMTP
  server
  -# [_smtp_auth_]              - Should we use SMTP authentication (true or
  false)
  -# [_smtp_username_]          - Username to use for SMTP authentication (if
  being used)
  -# [_smtp_password_]          - Password to use for SMTP authentication (if
  being used)
  -# [_password_sender_]        - Password reminder email address
  -# [_emergency_contact_]      - Site admin email address
  +# [_db_name_]        - name of the mediawiki instance mysql database
  +# [_db_user_]        - name of the mysql database user
  +# [_db_password_]    - password for the mysql database user
  +# [_ip_]             - ip address of the mediawiki web server
  +# [_port_]           - port on mediawiki web server
  +# [_server_aliases_] - an array of mediawiki web server aliases
  +# [_ensure_]         - the current status of the wiki instance
  +#                    - options: present, absent, deleted
  #
  # === Examples
  #
  @@ -60,18 +46,16 @@ define mediawiki::instance (
  $port                   = '80',
  $server_aliases         = '',
  $ensure                 = 'present',
-  $allow_html_email       = 'false',
-  $allow_html_email      = 'false',
  $additional_mail_params = 'none',
  $logo_url               = false,
  $external_smtp          = false,
-  $smtp_idhost=undef,
-  $smtp_host=undef,
-  $smtp_port=undef,
-  $smtp_auth=false,
-  $smtp_username='',
-  $smtp_password='',
-  $password_sender='apache@localhost',
-  $emergency_contact='apache@localhost',
-  $smtp_idhost,
-  $smtp_host,
-  $smtp_port,
-  $smtp_auth,
-  $smtp_username,
-  $smtp_password,
  ) {
  
  validate_re($ensure, '^(present|absent|deleted)$',
  @@ -97,13 +81,12 @@ define mediawiki::instance (
   if ! $smtp_idhost   { fail("'smtp_idhost' required when
  'external_smtp' is true.") }
   if ! $smtp_host     { fail("'smtp_host' required when 'external_smtp'
  is true.") }
   if ! $smtp_port     { fail("'smtp_port' required when 'external_smtp'
  is true.") }
-    if $smtp_auth     {
-        if ! $smtp_username { fail("'smtp_username' required when
  'smtp_auth' is true.") }
-        if ! $smtp_password { fail("'smtp_password' required when
  'smtp_auth' is true.") }
-      }
-    $smtp_settings = "array('host' => \"${smtp_host}\", 'IDHost' =>
  \"${smtp_idhost}\", 'localhost' => \"${::hostname}.${smtp_idhost}\", 'port'
  => 25, 'auth' => ${smtp_auth}, 'username' => \"${smtp_username}\",
  'password' => \"${smtp_password}\");"
-    if ! $smtp_auth     { fail("'smtp_auth' required when 'external_smtp'
  is true.") }
-    if ! $smtp_username { fail("'smtp_username' required when
  'external_smtp' is true.") }
-    if ! $smtp_password { fail("'smtp_password' required when
  'external_smtp' is true.") }
-    $wgsmtp = "array('host' => '${smtp_host}', 'idhost' =>
  '${smtp_idhost}', 'port' => '${smtp_port}', 'auth' => '${smtp_auth}',
  'username' => '${smtp_username}', 'password' => '${smtp_password}')"
  } else {
-    $smtp_settings = "false;"
-    $wgsmtp = "false"
  }
  
  # Figure out how to improve db security (manually done by
  
  @@ -125,7 +108,7 @@ define mediawiki::instance (
                       --dbname ${db_name}                       \
                       --dbuser ${db_user}                       \
                       --dbpass ${db_password}                   \
-                        --dbprefix ${db_prefix}                  \
-                        --db-prefix ${db_prefix}                  \
                       --confpath ${mediawiki_conf_dir}/${name}  \
                       --lang en",
       creates     => "${mediawiki_conf_dir}/${name}/LocalSettings.php",
  @@ -135,8 +118,8 @@ define mediawiki::instance (
     # Ensure resource attributes common to all resources
     File {
       ensure => directory,
-        owner  => "${mediawiki::params::apache_user}",
-        group  => "${mediawiki::params::apache_user}",
-        owner  => 'apache',
-        group  => 'apache',
       mode   => '0755',
     }

@@ -145,46 +128,28 @@ define mediawiki::instance (
         file_line{"${name}_logo_url":
           path  =>  "${mediawiki_conf_dir}/${name}/LocalSettings.php",
           line  =>  "\$wgLogo = '${logo_url}';",
- ```
       match =>  '\$wgLogo =.*$',
   }
  ```
  
     }
- ```
   # SMTP settings
  ```
-      file_line{"${name}_smtp":
-        path  =>  "${mediawiki_conf_dir}/${name}/LocalSettings.php",
-        line  =>  "\$wgSMTP = ${smtp_settings}",
-        match =>  '\$wgSMTP =.*$',

## \-      }
-      # Emergency contact
-      file_line{"${name}_emergency_contact":
-        path  =>  "${mediawiki_conf_dir}/${name}/LocalSettings.php",
-        line  =>  "\$wgEmergencyContact = '${emergency_contact}';",
-        match =>  '\$wgEmergencyContact =.*$',

## \-      }
-      # Password sender
-      file_line{"${name}_password_sender":
-        path  =>  "${mediawiki_conf_dir}/${name}/LocalSettings.php",
-        line  =>  "\$wgPasswordSender = '${password_sender}';",
-        match =>  '\$wgPasswordSender =.*$',

## \-      }

```
   # MediaWiki instance directory
   file { "${mediawiki_conf_dir}/${name}":
     ensure   => directory,
   }
```

-#      # MediaWiki DefaultSettings
-#      file { "${mediawiki_conf_dir}/${name}/includes/DefaultSettings.php":
-#        ensure  =>  present,
-#        content =>  template('mediawiki/DefaultSettings.php.erb'),
-#      }
-      # MediaWiki DefaultSettings
-      file { "${mediawiki_conf_dir}/${name}/includes/DefaultSettings.php":
-        ensure  =>  present,
-        content =>  template('mediawiki/DefaultSettings.php.erb'),
- ```
   }
  ```
  
     # Each instance needs a separate folder to upload images
     file { "${mediawiki_conf_dir}/${name}/images":
       ensure   => directory,
-        group  => "${mediawiki::params::apache_user}",
-        group => $::operatingsystem ? {
-          /(?i)(redhat|centos)/ => 'apache',
-          /(?i)(debian|ubuntu)/ => 'www-data',
-          default               => undef,
- ```
     }
  ```
  
     }
  
     # Ensure that mediawiki configuration files are included in each
  instance.
  @@ -203,13 +168,13 @@ define mediawiki::instance (
  
     # Each instance has a separate vhost configuration
     apache::vhost { $name:
-        ensure        => $ensure,
       port          => $port,
       docroot       => $doc_root,
       serveradmin   => $admin_email,
       servername    => $server_name,
       vhost_name    => $ip,
       serveraliases => $server_aliases,
- ```
     ensure        => $ensure,
  ```
  
     }
   }
   'deleted': {
  @@ -229,17 +194,17 @@ define mediawiki::instance (
     }
  
     mysql::db { $db_name:
-        ensure   => 'absent',
       user     => $db_user,
       password => $db_password,
       host     => 'localhost',
       grant    => ['all'],
- ```
     ensure   => 'absent',
  ```
  
     }
  
     apache::vhost { $name:
-        ensure        => 'absent',
       port          => $port,
       docroot       => $doc_root,
- ```
     ensure        => 'absent',
  ```
  
     }
   }
  }
  diff --git a/manifests/params.pp b/manifests/params.pp
  index 28e61d4..4867f59 100644
  --- a/manifests/params.pp
  +++ b/manifests/params.pp
  @@ -21,8 +21,7 @@
  #
  class mediawiki::params {
-  $tarball_url        = '
  http://releases.wikimedia.org/mediawiki/1.23/mediawiki-1.23.1.tar.gz'
-  $mediawiki_dir = regsubst($tarball_url,
  '^._?/(mediawiki-\d.\d+.\d+)._$', '\1')
-  $tarball_url        = '
  http://releases.wikimedia.org/mediawiki/1.22/mediawiki-1.22.3.tar.gz'
  $conf_dir           = '/etc/mediawiki'
  $apache_daemon      = '/usr/sbin/apache2'
  $installation_files = ['api.php',
  @@ -55,19 +54,26 @@ class mediawiki::params {
                        'thumb.php',
                        'thumb.php5',
                        'wiki.phtml']
  -
  +
  case $::operatingsystem {
-    'Redhat', 'CentOS':  {
-    redhat, centos:  {
     $web_dir            = '/var/www/html'
     $doc_root           = "${web_dir}/wikis"
     $packages           = ['php-gd', 'php-mysql', 'php-xml', 'wget',
  'php-pecl-apcu', 'php-intl']
     $apache             = 'httpd'
     $apache_user        = 'apache'
   }
-    'Debian', 'Ubuntu':  {
-    debian:  {
-      $web_dir            = '/var/www'
-      $doc_root           = "${web_dir}/wikis"
-      $packages           = ['php5', 'php5-mysql', 'wget']
-      $apache             = 'apache2'
-      $apache_user        = 'www-data'
-    }
-    ubuntu:  {
     $web_dir            = '/var/www'
     $doc_root           = "${web_dir}/wikis"
-      $packages           = ['php5', 'php5-mysql', 'wget', 'php-mail',
  'php5-gd', 'php5-xcache', 'php5-intl']
-      $packages           = ['php5', 'php5-mysql', 'wget']
     $apache             = 'apache2'
     $apache_user        = 'www-data'
   }
  @@ -75,5 +81,4 @@ class mediawiki::params {
     fail("Module ${module_name} is not supported on
  ${::operatingsystem}")
   }
  }
-  $mediawiki_install_path = "${web_dir}/${mediawiki_dir}"
  }
  diff --git a/metadata.json b/metadata.json
  index fc256d0..e2a5d0b 100644
  --- a/metadata.json
  +++ b/metadata.json
  @@ -1,11 +1,12 @@
  {
-  "name": "aimonb/nexusis_mediawiki",
-  "version": "2.0.4",
-  "source": "https://github.com/NexusIS/puppet-mediawiki.git",
-  "author": "Aimon Bustardo",
-  "license": "Apache 2.0",
-  "name": "martasd-mediawiki",
-  "version": "0.3.0",
-  "source": "git@github.com:martasd/puppet-mediawiki.git",
-  "author": "Martin Dluhos",
-  "license": "GPLv3",
  "summary": "Puppet module for multi-tenant Mediawiki installation.",
-  "project_page": "https://github.com/NexusIS/puppet-mediawiki",
-  "description": "Deploy and manage multiple Mediawiki instances using
  only one installation.",
-  "project_page": "https://github.com/martasd/puppet-mediawiki",
  "dependencies": [
   {
     "name": "puppetlabs/apache",
  @@ -24,11 +25,30 @@
     "version_requirement": ">= 3.0.0"
   }
  ],
-  "operatingsystem_support": [
-      {"operatingsystem": "Redhat"},
-      {"operatingsystem": "CentOS"},
-      {"operatingsystem": "Ubuntu"},
-      {"operatingsystem": "Debian"}
-  "types": [
  +
  ],
-  "tags": ["mediawiki", "wiki"]
-  "checksums": {
-    "CHANGELOG": "af50d1c1d76211f95dc766ea097a7b9c",
-    "LICENSE": "d32239bcb673463ab874e80d47fae504",
-    "Modulefile": "6981868fec6f57137c02f90bc462134d",
-    "README.md": "69977b0bcaeab715e9a0b43f6354e24e",
-    "Rakefile": "f37e6131fe7de9a49b09d31596f5fbf1",
-    "lib/puppet/parser/functions/gen_target_path.rb":
  "0813a7a2e7cc994d4dd09f57e6dabde5",
-    "manifests/files.pp": "a4361aeebfa47c5b3d1d998ccc62593b",
-    "manifests/init.pp": "d7f09a44013f8889455786d15de9084e",
-    "manifests/instance.pp": "4805d8b693f92d48339ee98ba12e7881",
-    "manifests/params.pp": "730b8b3a2627f062b0710f0268fa8480",
-    "manifests/symlinks.pp": "2791d55959ec09768fc11899bc9528e5",
-    "spec/classes/mediawiki_spec.rb": "a366727f2750208d4f5a884b8aaeb9c5",
-    "spec/classes/params_spec.rb": "d474ee514887650f455b9b438b36b5d2",
-    "spec/defines/files_spec.rb": "5ef5607bb139d16fd77774167f20e3f5",
-    "spec/defines/instance_spec.rb": "828e31efac16e5391564dc94122ef952",
-    "spec/defines/symlinks_spec.rb": "3f827efb72c457ebb69270a8de7a3dcc",
-    "spec/fixtures/manifests/site.pp": "d41d8cd98f00b204e9800998ecf8427e",
-    "spec/spec.opts": "a600ded995d948e393fbe2320ba8e51c",
-    "spec/spec_helper.rb": "3ea886dd135e120afa31e0aab12e85b0",
-    "tests/init.pp": "31aeb3585739f13725ac0e04b26baa46",
-    "tests/instance.pp": "1d00ce3b80585811c8825174f5a51435"
-  }
  }
  \ No newline at end of file
  diff --git a/templates/DefaultSettings.php.erb
  b/templates/DefaultSettings.php.erb
  index 884d03b..3e735fc 100644
  --- a/templates/DefaultSettings.php.erb
  +++ b/templates/DefaultSettings.php.erb
  @@ -1374,7 +1374,7 @@ $wgSMTP = "<%= @wgsmtp ||= 'false' %>";
  - Additional email parameters, will be passed as the last argument to
    mail() call.
  - If using safe_mode this has no effect
    */
    -$wgAdditionalMailParams = "<%= @additional_mail_params ||= 'null' %>";
    +$wgAdditionalMailParams = <%= @additional_mail_params ||= 'null' %>;
  
  /**
  - For parts of the system that have been updated to provide HTML email
    content, send
    @@ -2568,8 +2568,8 @@ $wgBrowserBlackList = array(
    '/^Mozilla\/4.[^ ]+ [^(]_?((?!compatible)._; [UIN]/',
    
    /**
-     \* MSIE on Mac OS 9 is teh sux0r, converts Ã¾ to <thorn>, Ã° to <eth>,
-     \* Ãž to <THORN> and Ã� to <ETH>
-     \* MSIE on Mac OS 9 is teh sux0r, converts þ to <thorn>, ð to <eth>,
-     \* Þ to <THORN> and Ð to <ETH>
    *
  - Known useragents:
  - \- Mozilla/4.0 (compatible; MSIE 5.0; Mac_PowerPC)
    @@ -2674,7 +2674,7 @@ $wgDisabledVariants = array();
    -     $wgArticlePath = '/wiki/$1';
    - @endcode
      *
- \* A link to /wiki/ would be redirected to /sr/Ð“Ð»Ð°Ð²Ð½Ð°_Ñ�Ñ‚Ñ€Ð°Ð½Ð°
- \* A link to /wiki/ would be redirected to /sr/Главна_страна
  *
  - It is important that $wgArticlePath not overlap with possible values
  - of $wgVariantArticlePath.
    @@ -3647,7 +3647,7 @@ $wgUrlProtocols = array(
    'sip:',
    'sips:',
    'gopher://',
-    'telnet://', // Well if we're going to support the above.. -Ã¦var
-    'telnet://', // Well if we're going to support the above.. -ævar
   'nntp://', // @bug 3808 RFC 1738
   'worldwind://',
   'mailto:',
  diff --git a/tests/instance.pp b/tests/instance.pp
  index c753c10..77efbdc 100644
  --- a/tests/instance.pp
  +++ b/tests/instance.pp
  @@ -1,7 +1,7 @@
  mediawiki::instance { 'my_wiki1':
-  ensure      => 'present',
  db_password => 'super_long_password',
  db_name     => 'wiki1',
-  db_user     => 'wiki1_user',
-  db_user     => 'wiki1_user'
  port        => '80',
-  status      => 'present'
  }

2015-07-23 21:49 GMT+02:00 Aimon Bustardo notifications@github.com:

> I have hand merged your code internally. Once it goes through CI and
> testing it will be pushed here. HEAD of your form should be roughly the
> same as HEAD here once we have pushed the merged code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NexusIS/puppet-mediawiki/pull/5#issuecomment-124222278
> .

**Pull request merged**
